[package]
name = "example-bin"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
example-lib = { path = "../example-lib" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"